---
sidebar: sidebar 
permalink: trident-managing-k8s/uninstall-trident.html 
keywords: uninstall, astra trident, methods, operator, tridentctl, helm 
summary: 根据 Astra Trident 的安装方式，有多种卸载方法。 
---
= 卸载 Astra Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根据 Astra Trident 的安装方式，有多种卸载方法。



== 使用 Helm 卸载

如果您使用Helm安装了Astra Trident、则可以使用将其卸载 `helm uninstall`。

[listing]
----
#List the Helm release corresponding to the Astra Trident install.
helm ls -n trident
NAME          NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
trident       trident         1               2021-04-20 00:26:42.417764794 +0000 UTC deployed        trident-operator-21.07.1        21.07.1

#Uninstall Helm release to remove Trident
helm uninstall trident -n trident
release "trident" uninstalled
----


== 使用 Trident 操作符卸载

如果您使用操作符安装了 Astra Trident ，则可以通过执行以下操作之一卸载它：

* *编辑 `TridentOrchestrator` 要设置卸载标志：*您可以编辑 `TridentOrchestrator` 并设置 `spec.uninstall=true`。编辑 `TridentOrchestrator` CR并设置 `uninstall` 标记如下所示：
+
[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"uninstall":true}}'
----
+
当 `uninstall` 标志设置为 `true`、Trident操作符将卸载Trident、但不会删除Trident Orchestrator本身。如果需要、您应清理TridentOrchestrator并创建一个新的
重新安装三端到端。

* *删除 `TridentOrchestrator`：通过删除 `TridentOrchestrator` cr用于部署Astra Trident、此时您需要指示操作员卸载Trident。操作员将处理的删除操作 `TridentOrchestrator` 然后继续删除Astra Trident部署和取消定义、并删除在安装过程中创建的Trident Pod。
要完全删除Astra Trident (包括其创建的CRD)并有效地擦除板、您可以进行编辑 `TridentOrchestrator` 以传递 `wipeout` 选项请参见以下示例：


[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"wipeout":["crds"],"uninstall":true}}'
----
这将完全卸载 Astra Trident 并清除与后端及其管理的卷相关的所有元数据。后续安装将视为全新安装。


WARNING: 只有在执行完全卸载时，才应考虑擦除 CRD 。此操作无法撤消。* 除非您希望重新启动并创建全新的 Astra Trident 安装，否则请勿擦除 CRD 。



== 使用卸载 `tridentctl`

运行 `uninstall` 命令输入 `tridentctl` 如下所示、删除除CRD和相关对象之外与Astra Trident关联的所有资源、从而可以轻松地重新运行安装程序以更新到最新版本。

[listing]
----
./tridentctl uninstall -n <namespace>
----
要完全删除 Astra Trident ，您应删除由 Astra Trident 创建的 CRD 的最终结果并删除这些 CRD 。
